name: Actions

on:
  pull_request: {}
  push: { branches: [master, merge_requests] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          lfs: true

      # Linter
      - name: Run Linter
        run: |
            git clone "https://github.com/rookxx/StyleCopAnalyzers.CLI.git" ../linter
            STYLE_CHECK_COMMAND="dotnet ../linter/tools/bin/style/StyleCopAnalyzers.CLI.dll check Assets/Scenes"
            STYLE_CHECK_RESULT=`${STYLE_CHECK_COMMAND}`
            echo "${STYLE_CHECK_RESULT}"
            [[ -z "${STYLE_CHECK_RESULT}" ]]