name: Actions

on:
  pull_request: {}
  push: { branches: [master, merge_requests] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project
    runs-on: [self-hosted, linux]
    steps:
      # Activate
      - name: Unity - Activate
        uses: webbertakken/unity-activate@v1.3

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2.1.3
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.7
        with:
          unityVersion: 2019.4.14f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v1.5
        with:
          unityVersion: 2019.4.14f1
          targetPlatform: StandaloneWindows64

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build